name: bildform
favicon: null
layout_spectrum: 0.94862
typography_spectrum: 0.96979
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f1f9'
    - '#2e2925'
    - '#c5b89e'
    - '#000000'
    - '#817a19'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
